### ISSUE TITLE
100daysofpython Tracker

### ISSUE THREAD

**Issue by labanonpaul** [labanonpaul/100daysofpython#1]
**Beginner Python**
- [ ] Variables in Python
- [ ] String Manipulation
- [ ] Input and Print Functions
- [ ] Variable Naming Rules
- [ ] Mathematical Operations in Python
- [ ] DataTypes
- [ ] Converting types
- [ ] Conditionals IF/ELIF/ELSE
- [ ] Logical Operators
- [ ] Randomisation
- [ ] Error Handling
- [ ] Functions
- [ ] For Loops
- [ ] Code blocks and Indentation
- [ ] While Loops
- [ ] Flowchart Programming
- [ ] Positional and Keyword Arguments
- [ ] Python Dictionaries and Lists
- [ ] Nested Collections
- [ ] Returning Functions
- [ ] Return vs. Print
- [ ] Doc Strings vs. Comments
- [ ] Scope and Local/Global Variables
- [ ] Debugging Techniques

**Intermediate Python**
- [ ] Local Development Environment Setup
- [ ] PyCharm Tips and Tricks
- [ ] Python Object Oriented Programming
- [ ] Creating Classes in Python
- [ ] Using External Python Modules/Import
- [ ] Getting / Setting Attributes
- [ ] Python Methods
- [ ] Class Initialisers
- [ ] Module Aliasing
- [ ] Optional, Required and Default Parameters
- [ ] Event Listenters
- [ ] Python Instances and State
- [ ] Python Turtle
- [ ] Game Development with Python and OOP
- [ ] Python Inheritance
- [ ] Python Slice Function
- [ ] File I/O Reading and Writing to Local Files
- [ ] File Directories
- [ ] Reading and Writing to CSV
- [ ] Introduction to the Pandas Framework
- [ ] List Comprehensions
- [ ] Dictionary Comprehensions
- [ ] Packing and Unpacking Functions in Python
- [ ] Creating Desktop GUI Apps with Tkinter
- [ ] Strongly Dynamic Typing
- [ ] Error Handling and Exceptions
- [ ] Try / Except/ Raise
- [ ] Working with JSONs
- [ ] Local Persistence
- [ ] Sending Email with Python and SMTP
- [ ] Working with date and time
- [ ] Hosting Python Code Online with PythonAnywhere
- [ ] APIs
- [ ] Making HTTP Requests with the Requests module
- [ ] Sending Parameters with the Request
- [ ] APIs with Authentication
- [ ] Sending SMS with Python
- [ ] Web Scraping with Beautiful Soup
- [ ] Browser Automation with Selenium Web Driver
- [ ] Automating Tinder
- [ ] Automating Twitter
- [ ] Automating LinkedIn
- [ ] Automating Instagram
- [ ] Web Development with Flask
- [ ] Command Line
- [ ] Python Decorators
- [ ] Templating with Jinja 2
- [ ] WTForms

**Advanced Python**
- [ ] Build Your Own REST API with Python
- [ ] Build Your Own Blog
- [ ] Databases with SQLite
- [ ] Dataframe Inspection
- [ ] Data Cleaning
- [ ] Sorting Values in Dataframes
- [ ] Arithmatic Operations with Pandas
- [ ] Creating Pivot Tables
- [ ] Chaining Functions
- [ ] Smoothing Time Series Data
- [ ] Creating Line Charts with Matplotlib
- [ ] Using Jupyter Notebook
- [ ] HTML Markdown
- [ ] Creating Scatterplots with Matplotlib
- [ ] Relational Database Schemas
- [ ] Descriptive Statistics
- [ ] Creating Bar Charts, Pie Charts, Donut Charts, Box Plots with
- [ ] Plotly
- [ ] Creating NumPy NDArrays
- [ ] Array Slicing and Subsetting
- [ ] Matrix Multiplication
- [ ] Bitwise and Operators in Pandas
- [ ] Creating Bubble Charts with Seaborn
- [ ] Running Regressions with Scikit-Learn
- [ ] Non-Parametric Regression
- [ ] Students T-Tests and Histograms with Scikit-Learn
- [ ] Multi-Variable Regression
- [ ] Log Transformations
- [ ] Residuals Analysis
- [ ] Text to Morse Code Converter
- [ ] Portfolio Website
- [ ] Tic Tac Toe Game
- [ ] Image Watermarking App
- [ ] Typing Speed Test
- [ ] Breakout Game
- [ ] Cafe and Wifi Website
- [ ] Todo List Website
- [ ] Disappearing Text Writing App
- [ ] Image Color Palette Generator
- [ ] Custom Web Scraper
- [ ] Automating the Google Dinosaur Game
- [ ] Space Invaders Game
- [ ] Custom API Driven Website
- [ ] An Online Shop
- [ ] Custom Browser Automation
- [ ] Analyse and Visualise the Space Race
- [ ] Analyse Deaths Involving the Police in the US
- [ ] Predict Earnings using Multivariable Regression
